### PR TITLE
fix: Inability to draw with active filter

### LINKED ISSUE #136: Inability to draw with active filter
### Abstract (Enhancement)
Currently, it is not possible to draw points with active filter. This results in enforcing users to first draw the points and then filter, which itself results in a flashy UI. 

### What triggered the issue
Users may want to change the point values for the `colorBy`. For example, you want to color by for different `Value A`. In order to do this with the current API, the only way is to redraw by passing a new points object. (E.G `[[x,y,A,B]...`).

However, while doing this, you may have active filter applied. The filter is reset on the `.draw` call.

### Proposal

To improve the user experience, it would be useful to be able to set `filteredPoints` while drawing already, or give the ability for users to pass new data objects for the points without needing to redraw (I guess this may be more complex)

- [x] Check for duplicate issues.
- [x] Describe the bug: what did you do to trigger it, what was your expected behavior, and what did you experience instead.
- [x] Use the latest versions of `regl-scatterplot`.

### PR DESCRIPTION
**Pull request by insertmike**
Adds `preventFilterReset` option to `ScatterplotMethodOptions['draw']` to allow re-drawing while keeping the current active filter.

## Description

> What was changed in this pull request?

- Added `preventFilterReset` option to `ScatterplotMethodOptions['draw']`

> Why is it necessary?

Fixes #136 

## Checklist

- [x] Provided a concise title as a [semantic commit message](https://www.conventionalcommits.org) (e.g. "fix: correctly handle undefined properties")
- [x] `CHANGELOG.md` updated
- [x] Tests added or updated
- [x] Documentation in `README.md` added or updated

### CODE REVIEW

**Comment by insertmike** [comment]
@flekschas Does this look good?

File: src/index.js [hunk 1]
```diff
@@ -2274,12 +2274,18 @@ const createScatterplot = (
             return;
           }
 
-          // Reset filter
-          isPointsFiltered = false;
-          filteredPointsSet.clear();
-
           let pointsCached = false;
+
+          if (!options.preventFilterReset) {
```
Comment (flekschas) [inline src/index.js:2279]:
```suggestion
          if (!options.preventFilterReset || points?.length !== numPoints) {
```

File: src/index.js [hunk 2]
```diff
@@ -2274,12 +2274,18 @@ const createScatterplot = (
...
+              isPointsFiltered = false;
+              filteredPointsSet.clear();
+          }
           if (points) {
+            if (points.length !== numPoints) {
+              // Reset filter every time number of points changed
+              isPointsFiltered = false;
+              filteredPointsSet.clear();
+            }
```
Comment (flekschas) [inline src/index.js:2288]:
```suggestion
```

This can be merged into the above if statement. See my comment

**Review by flekschas — CHANGES_REQUESTED** [review]
Thanks for taking a stab at the issue. The code looks good overall but I left some comments for smaller adjustments

File: README.md [hunk 3]
```diff
@@ -517,6 +517,7 @@ Zoom to a specific area specified by a recangle in normalized device coordinates
   - `transition` [default: `false`]: if `true`, the camera will smoothly transition to its new position
   - `transitionDuration` [default: `500`]: the duration in milliseconds over which the transition should occur
   - `transitionEasing` [default: `cubicInOut`]: the easing function, which determines how intermediate values of the transition are calculated
+  - `preventFilterReset` [default: `true`]: if `false`, the active filteredPoints set is not being reset.
```
[the remark this answers is not in the document]
Comment (insertmike) [reply README.md:520]: My wrong. Good call!

**Comment by insertmike** [comment]
Thanks for your dedication and review! @flekschas

I went through your code review and trying addressing all comments.

**Review by flekschas — APPROVED** [review]
Thanks for addressing my comments! The PR looks good now!

**Comment by insertmike** [comment]
> Thanks for addressing my comments! The PR looks good now!

Amazing, thank you! Looking forward to more PR's. Are we planning on having a release anytime soon?

**Comment by flekschas** [comment]
Yes, a release is imminent. Just putting another fix together
